from pydantic import BaseModel, Field


class SPARQLQuery(BaseModel):
    query: str = Field(description="SPARQL 1.1 query string")


class SPARQLResult(BaseModel):
    bindings: list[dict[str, str]] = Field(default_factory=list)
    vars: list[str] = Field(default_factory=list)


class SPARQLUpdate(BaseModel):
    update: str = Field(description="SPARQL 1.1 Update string")


class NLQuery(BaseModel):
    question: str = Field(min_length=1, max_length=2000)
    kg_name: str | None = Field(default=None, description="Query a specific knowledge graph")
    model: str | None = Field(default=None, description="Override the query generation model (OpenRouter model ID)")
    exclude_questions: list[str] = Field(default_factory=list, description="Questions to exclude from example bank retrieval (anti-cheat for evals)")


class FactCitation(BaseModel):
    """Per-cited-fact honesty metadata for an answer (ONTA-280, P7 answer layer).

    Attached to a fact the answer relies on, carrying its recency (from the
    Wave-3 valid-time interval: ``valid_from`` + ``is_current`` == absence of a
    ``valid_to``), its ``verdict`` (``current`` / ``superseded`` / ``retracted`` /
    ``lost_conflict``), and its ``confidence`` (from the companion provenance
    graph — ``None`` when provenance is disabled/absent). Purely additive and
    read-only: a fact with no validity node is ``current`` by convention.

    ``truth_verdict`` is the SEPARATE A4 EPISTEMIC verdict (ONTA-375): whether
    independent evidence corroborates the fact (``supported`` / ``refuted`` /
    ``unverifiable`` / ``identity_conditional``), read from the per-attribute
    ``attr_meta/`` truth-verdict companion the A4 Verify seam persists. This is the
    TRUTH axis and is DISTINCT from the recency/validity ``verdict`` above — a fact
    can be ``current`` AND ``unverifiable`` at once. Empty when no verdict companion
    exists (verification was off at ingest, or the row is not a literal attribute).
    """

    subject: str = ""
    predicate: str = ""
    object: str = ""
    label: str = ""
    verdict: str = ""
    confidence: float | None = None
    valid_from: str = ""
    is_current: bool = True
    source: str = ""
    truth_verdict: str = ""


class NLResult(BaseModel):
    answer: str
    sparql: str
    explanation: str
    ontology: str = Field(default="", description="Ontology summary text passed to the LLM for SPARQL generation")
    narrative_answer: str = Field(default="", description="Natural-language summary of the result set, generated by a fast LLM")
    functions_invoked: list[str] = Field(default_factory=list)
    timing: dict[str, float | str] = Field(default_factory=dict, description="Stage latencies in ms and metadata")
    # ONTA-280 (P7 answer layer): per-cited-fact verdict/confidence/recency, and a
    # coverage caveat ("answered from N of M sources; K facts stale"). Both default
    # empty so every existing caller / test is back-compatible; populated only when
    # COGRAPH_ANSWER_CITATIONS_ENABLED is set (see nlp/pipeline.py).
    citations: list[FactCitation] = Field(default_factory=list, description="Per-fact verdict/confidence/recency for the facts the answer relies on")
    coverage_caveat: str = Field(default="", description="Honest coverage caveat: 'answered from N of M sources; K facts stale'")
