export { Client, CographError, RawApi } from "./client.js";
export type {
  ClientOptions,
  IngestOptions,
  AskOptions,
  AgentTurnOptions,
  AgentResult,
  ResolvedChange,
  OntologyResolveResult,
  OntologyApplyResult,
  EnrichRequest,
  EnrichJob,
  EnrichJobCreate,
  JobProgress,
  JobSummary,
  Verdict,
  ConflictReview,
  RowResult,
  EnrichmentTier,
  JobStatus,
  ConflictPolicy,
  RowAction,
  ReviewDecision,
  // COG-128 — raw/passthrough API + newly-added typed shapes
  RawInit,
  TypeRecord,
  TypeRecordsPage,
  TypeEdge,
  NormalizationRule,
  // ONTA-178 — canonical semantic instance search
  SemanticSearchHit,
  SemanticSearchResponse,
} from "./client.js";
