from pydantic import BaseModel, Field


class SPARQLQuery(BaseModel):
    query: str = Field(description="SPARQL 1.1 query string")


class SPARQLResult(BaseModel):
    bindings: list[dict[str, str]] = Field(default_factory=list)
    vars: list[str] = Field(default_factory=list)


class SPARQLUpdate(BaseModel):
    update: str = Field(description="SPARQL 1.1 Update string")


class ConversationTurn(BaseModel):
    """One prior chat turn for /ask follow-ups (same shape as agent Turn)."""

    role: str = Field(default="user", pattern=r"^(user|assistant)$")
    text: str = Field(default="", max_length=4000)


class NLQuery(BaseModel):
    question: str = Field(min_length=1, max_length=2000)
    # ONTA-414: the SAME pattern create enforces (KGCreate.name). kg_name is
    # interpolated into a graph IRI inside generated SPARQL (`FROM <...>`), so a
    # name carrying ">" would close the IRI early and let a second FROM naming
    # ANOTHER tenant's graph be injected. "*" (not "+") so an explicit empty
    # string keeps its existing meaning of "no KG selected, use the tenant graph".
    kg_name: str | None = Field(
        default=None,
        pattern=r"^[a-zA-Z0-9_-]*$",
        description="Query a specific knowledge graph",
    )
    model: str | None = Field(default=None, description="Override the query generation model (OpenRouter model ID)")
    exclude_questions: list[str] = Field(default_factory=list, description="Questions to exclude from example bank retrieval (anti-cheat for evals)")
    session_id: str | None = Field(
        default=None,
        description="Optional conversation id; loads prior turns from the agent store",
    )
    conversation: list[ConversationTurn] = Field(
        default_factory=list,
        description="Optional prior turns when the client already has the transcript",
    )


class FactCitation(BaseModel):
    """Per-cited-fact honesty metadata for an answer (ONTA-280, P7 answer layer).

    Attached to a fact the answer relies on, carrying its recency (from the
    Wave-3 valid-time interval: ``valid_from`` + ``is_current`` == absence of a
    ``valid_to``), its ``verdict`` (``current`` / ``superseded`` / ``retracted`` /
    ``lost_conflict``), and its ``confidence`` (from the companion provenance
    graph — ``None`` when provenance is disabled/absent). Purely additive and
    read-only: a fact with no validity node is ``current`` by convention.

    ``truth_verdict`` is the SEPARATE A4 EPISTEMIC verdict (ONTA-375): whether
    independent evidence corroborates the fact (``supported`` / ``refuted`` /
    ``unverifiable`` / ``identity_conditional``), read from the per-attribute
    ``attr_meta/`` truth-verdict companion the A4 Verify seam persists. This is the
    TRUTH axis and is DISTINCT from the recency/validity ``verdict`` above — a fact
    can be ``current`` AND ``unverifiable`` at once. Empty when no verdict companion
    exists (verification was off at ingest, or the row is not a literal attribute).
    """

    subject: str = ""
    predicate: str = ""
    object: str = ""
    label: str = ""
    verdict: str = ""
    confidence: float | None = None
    valid_from: str = ""
    is_current: bool = True
    source: str = ""
    truth_verdict: str = ""


class NLResult(BaseModel):
    answer: str
    sparql: str
    explanation: str
    ontology: str = Field(default="", description="Ontology summary text passed to the LLM for SPARQL generation")
    narrative_answer: str = Field(default="", description="Natural-language summary of the result set, generated by a fast LLM")
    functions_invoked: list[str] = Field(default_factory=list)
    timing: dict[str, float | str] = Field(default_factory=dict, description="Stage latencies in ms and metadata")
    # ONTA-280 (P7 answer layer): per-cited-fact verdict/confidence/recency, and a
    # coverage caveat ("answered from N of M sources; K facts stale"). Both default
    # empty so callers that ignore them stay back-compatible; always populated
    # on the live ask path (see nlp/pipeline.py).
    citations: list[FactCitation] = Field(default_factory=list, description="Per-fact verdict/confidence/recency for the facts the answer relies on")
    coverage_caveat: str = Field(default="", description="Honest coverage caveat: 'answered from N of M sources; K facts stale'")
    # ONTA-389: trackable answer run id (= EnrichJob id, category=answer). Empty
    # when no job store is available. Operator path:
    # GET /operator/jobs/{run_id}/trace → P7 Answer (A7) + P0/A9.
    run_id: str = Field(
        default="",
        description=(
            "Answer-run id for operator Job Trace (P7/A7 + P0/A9). "
            "Look up via GET /operator/jobs/{run_id}/trace. Empty when tracking "
            "is unavailable."
        ),
    )
    # Whitepaper v3 / tokens-to-complete-task: one entry per LLM call on the
    # /ask path (sparql_gen, retry, rephrase, …). Default empty so every
    # existing caller / test is back-compatible; populated only when the
    # provider returned a usage object (or at least model/provider metadata).
    token_usage: list[dict] = Field(
        default_factory=list,
        description=(
            "Per-LLM-call token usage events for this /ask: "
            "stage, attempt, model, prompt_tokens, completion_tokens, "
            "total_tokens, provider. Empty when no LLM usage was recorded."
        ),
    )
    # Query plan confidence (filter-miss / constraint coverage gate).
    # high | medium | low; empty when the gate did not run (non-Cypher path).
    query_confidence: str = Field(
        default="",
        description=(
            "Plan confidence after constraint coverage: high | medium | low. "
            "Empty when not assessed."
        ),
    )
    query_confidence_reason: str = Field(
        default="",
        description="Short reason for query_confidence (debug / CLI -d).",
    )
    clarification_prompt: str = Field(
        default="",
        description=(
            "When confidence is low / fail-closed, an optional clarification "
            "question (which field a filter token should bind to)."
        ),
    )
