"""Normalized smoke-template Cypher used by the in-memory store dispatcher.

``_norm_cypher`` collapses whitespace so template MATCH/MERGE strings
compare equal to the literals in :mod:`schema_bootstrap` /
:mod:`rdfs_helpers`. ``MemoryGraphStore._execute`` dispatches on these.
"""

from __future__ import annotations

import re

from infona_client.graph.rdfs_helpers import (
    ENTITIES_OF_TYPE_COUNT_CYPHER,
    ENTITIES_OF_TYPE_CYPHER,
    LITERAL_AGGREGATE_CYPHER,
    LITERAL_COMPARE_CYPHER,
    LITERAL_VALUES_COUNT_CYPHER,
    LITERAL_VALUES_CYPHER,
    RELATED_ENTITIES_CYPHER,
    RELATED_ENTITY_NAME_FILTER_CYPHER,
    SUBCLASS_OF_CLOSURE_CYPHER,
)
from infona_client.graph.normalize_cypher import (
    ENTITY_LITERALS_BY_PROP_CYPHER,
    ENTITY_ORPHANS_OF_TYPE_CYPHER,
    ENTITY_RELS_BY_ATTR_CYPHER,
)
from infona_client.graph.schema_bootstrap import (
    ENTITY_1HOP_OUT_CYPHER,
    ENTITY_COUNT_BY_PRIMARY_TYPE_CYPHER,
    ENTITY_COUNT_BY_TYPE_CYPHER,
    ENTITY_COUNT_TOTAL_CYPHER,
    ENTITY_DETAIL_CYPHER,
    ENTITY_FILTER_PROP_EQ_CYPHER,
    ENTITY_GET_CYPHER,
    ENTITY_LIST_BY_TYPE_CYPHER,
    ENTITY_LIST_BY_TYPE_PAGE_CYPHER,
    ENTITY_LITERAL_GREP_CYPHER,
    ENTITY_MERGE_CYPHER,
    ENTITY_RELS_CYPHER,
    ENTITY_TYPE_ATTR_COVERAGE_CYPHER,
    ENTITY_TYPE_PROP_DISTINCT_CYPHER,
    ENTITY_TYPE_REL_COVERAGE_CYPHER,
    ENTITY_TYPE_REL_TARGET_DISTINCT_CYPHER,
    ONTO_ATTR_DELETE_CYPHER,
    ONTO_ATTR_LIST_CYPHER,
    ONTO_ATTR_RANGE_TYPE_CYPHER,
    ONTO_ATTR_SET_MARKERS_CYPHER,
    ONTO_ATTR_SET_TEXT_KIND_CYPHER,
    ONTO_ATTR_UPSERT_CYPHER,
    ONTO_SUBCLASS_CLEAR_CYPHER,
    ONTO_SUBCLASS_SET_CYPHER,
    ONTO_TYPE_DELETE_CYPHER,
    ONTO_TYPE_GET_CYPHER,
    ONTO_TYPE_LIST_CYPHER,
    ONTO_TYPE_SET_MARKERS_CYPHER,
    ONTO_TYPE_UPSERT_CYPHER,
)


def _norm_cypher(cypher: str) -> str:
    return re.sub(r"\s+", " ", cypher.strip())


_MERGE_NORM = _norm_cypher(ENTITY_MERGE_CYPHER)
_GET_NORM = _norm_cypher(ENTITY_GET_CYPHER)
_LIST_NORM = _norm_cypher(ENTITY_LIST_BY_TYPE_CYPHER)
_LIST_PAGE_NORM = _norm_cypher(ENTITY_LIST_BY_TYPE_PAGE_CYPHER)
_COUNT_BY_TYPE_SINGLE_NORM = _norm_cypher(ENTITY_COUNT_BY_TYPE_CYPHER)
_COUNT_TOTAL_NORM = _norm_cypher(ENTITY_COUNT_TOTAL_CYPHER)
_DETAIL_NORM = _norm_cypher(ENTITY_DETAIL_CYPHER)
_RELS_NORM = _norm_cypher(ENTITY_RELS_CYPHER)
_TYPE_ATTR_COVERAGE_NORM = _norm_cypher(ENTITY_TYPE_ATTR_COVERAGE_CYPHER)
_TYPE_REL_COVERAGE_NORM = _norm_cypher(ENTITY_TYPE_REL_COVERAGE_CYPHER)
_TYPE_PROP_DISTINCT_NORM = _norm_cypher(ENTITY_TYPE_PROP_DISTINCT_CYPHER)
_TYPE_REL_TARGET_DISTINCT_NORM = _norm_cypher(ENTITY_TYPE_REL_TARGET_DISTINCT_CYPHER)
_LITERAL_GREP_NORM = _norm_cypher(ENTITY_LITERAL_GREP_CYPHER)
_FILTER_PROP_EQ_NORM = _norm_cypher(ENTITY_FILTER_PROP_EQ_CYPHER)
_HOP_OUT_NORM = _norm_cypher(ENTITY_1HOP_OUT_CYPHER)
_ENTITIES_OF_TYPE_NORM = _norm_cypher(ENTITIES_OF_TYPE_CYPHER)
_ENTITIES_OF_TYPE_COUNT_NORM = _norm_cypher(ENTITIES_OF_TYPE_COUNT_CYPHER)
_LITERAL_VALUES_NORM = _norm_cypher(LITERAL_VALUES_CYPHER)
_LITERAL_VALUES_COUNT_NORM = _norm_cypher(LITERAL_VALUES_COUNT_CYPHER)
_LITERAL_COMPARE_NORM = _norm_cypher(LITERAL_COMPARE_CYPHER)
_LITERAL_AGGREGATE_NORM = _norm_cypher(LITERAL_AGGREGATE_CYPHER)
_RELATED_ENTITIES_NORM = _norm_cypher(RELATED_ENTITIES_CYPHER)
_RELATED_ENTITY_NAME_FILTER_NORM = _norm_cypher(RELATED_ENTITY_NAME_FILTER_CYPHER)
_SUBCLASS_OF_CLOSURE_NORM = _norm_cypher(SUBCLASS_OF_CLOSURE_CYPHER)
_ONTO_TYPE_UPSERT_NORM = _norm_cypher(ONTO_TYPE_UPSERT_CYPHER)
_ONTO_SUBCLASS_SET_NORM = _norm_cypher(ONTO_SUBCLASS_SET_CYPHER)
_ONTO_SUBCLASS_CLEAR_NORM = _norm_cypher(ONTO_SUBCLASS_CLEAR_CYPHER)
_ONTO_TYPE_LIST_NORM = _norm_cypher(ONTO_TYPE_LIST_CYPHER)
_ONTO_TYPE_GET_NORM = _norm_cypher(ONTO_TYPE_GET_CYPHER)
_ONTO_ATTR_UPSERT_NORM = _norm_cypher(ONTO_ATTR_UPSERT_CYPHER)
_ONTO_ATTR_RANGE_NORM = _norm_cypher(ONTO_ATTR_RANGE_TYPE_CYPHER)
_ONTO_ATTR_SET_TEXT_KIND_NORM = _norm_cypher(ONTO_ATTR_SET_TEXT_KIND_CYPHER)
_ONTO_ATTR_LIST_NORM = _norm_cypher(ONTO_ATTR_LIST_CYPHER)
_ONTO_ATTR_DELETE_NORM = _norm_cypher(ONTO_ATTR_DELETE_CYPHER)
_ONTO_TYPE_DELETE_NORM = _norm_cypher(ONTO_TYPE_DELETE_CYPHER)
_ONTO_ATTR_SET_MARKERS_NORM = _norm_cypher(ONTO_ATTR_SET_MARKERS_CYPHER)
_ONTO_TYPE_SET_MARKERS_NORM = _norm_cypher(ONTO_TYPE_SET_MARKERS_CYPHER)
_ENTITY_COUNT_BY_TYPE_NORM = _norm_cypher(ENTITY_COUNT_BY_PRIMARY_TYPE_CYPHER)
# Normalization rule-apply reads (ONTA-534).
_NORM_LITERALS_BY_PROP_NORM = _norm_cypher(ENTITY_LITERALS_BY_PROP_CYPHER)
_NORM_RELS_BY_ATTR_NORM = _norm_cypher(ENTITY_RELS_BY_ATTR_CYPHER)
_NORM_ORPHANS_OF_TYPE_NORM = _norm_cypher(ENTITY_ORPHANS_OF_TYPE_CYPHER)
